/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

/**
 *
 * @author Alejandra G
 */
public class InterfazCartas extends javax.swing.JFrame {
    public Juego juego;
    /**
     * Creates new form InterfazCartas
     */
    public InterfazCartas(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSolucion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lbBT1 = new javax.swing.JLabel();
        lbFB2 = new javax.swing.JLabel();
        lbFB3 = new javax.swing.JLabel();
        lbFB4 = new javax.swing.JLabel();
        lbFB5 = new javax.swing.JLabel();
        lbFB1 = new javax.swing.JLabel();
        lbBT2 = new javax.swing.JLabel();
        lbBT3 = new javax.swing.JLabel();
        lbBT4 = new javax.swing.JLabel();
        lbBT5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBT = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFB = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BackTracking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, 149, -1));

        txtSolucion.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtSolucion.setForeground(new java.awt.Color(255, 255, 255));
        txtSolucion.setText("La solución es:");
        jPanel1.add(txtSolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 860, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 108, 20));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fuerza Bruta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, 149, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 41, 58, -1));

        lbBT1.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbBT1.setForeground(new java.awt.Color(255, 255, 255));
        lbBT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBT1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbBT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 324, 93, 84));

        lbFB2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbFB2.setForeground(new java.awt.Color(255, 255, 255));
        lbFB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFB2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbFB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 175, 93, 84));

        lbFB3.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbFB3.setForeground(new java.awt.Color(255, 255, 255));
        lbFB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFB3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbFB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 175, 93, 84));

        lbFB4.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbFB4.setForeground(new java.awt.Color(255, 255, 255));
        lbFB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFB4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbFB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 175, 93, 84));

        lbFB5.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbFB5.setForeground(new java.awt.Color(255, 255, 255));
        lbFB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFB5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbFB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 175, 93, 84));

        lbFB1.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbFB1.setForeground(new java.awt.Color(255, 255, 255));
        lbFB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFB1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbFB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 175, 93, 84));

        lbBT2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbBT2.setForeground(new java.awt.Color(255, 255, 255));
        lbBT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBT2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbBT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 324, 93, 84));

        lbBT3.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbBT3.setForeground(new java.awt.Color(255, 255, 255));
        lbBT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBT3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbBT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 324, 93, 84));

        lbBT4.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbBT4.setForeground(new java.awt.Color(255, 255, 255));
        lbBT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBT4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbBT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 324, 93, 84));

        lbBT5.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        lbBT5.setForeground(new java.awt.Color(255, 255, 255));
        lbBT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBT5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbBT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 324, 93, 84));

        txtBT.setColumns(20);
        txtBT.setRows(5);
        jScrollPane1.setViewportView(txtBT);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 270, 130));

        txtFB.setColumns(20);
        txtFB.setRows(5);
        jScrollPane2.setViewportView(txtFB);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 270, 130));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cant. de resticciones: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 149, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 890, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setSolucion(String solucion){
        txtSolucion.setText("");
        txtSolucion.setText(solucion);
    }
    public void sugerenciaFB(String sospechoso,String arma,String motivo,String parte,String lugar){
        lbFB1.setText(sospechoso);
        lbFB2.setText(arma);
        lbFB3.setText(motivo);
        lbFB4.setText(parte);
        lbFB5.setText(lugar);
        String str = txtFB.getText() + "\n"+"["+sospechoso+","+arma+","+motivo+","+parte+","+lugar+"]";
        txtFB.setText(str);
    }
    public void solucionFB(String solucion){
        String str = txtFB.getText() + "\n"+solucion;
        txtFB.setText(str);
    }
    public void sugerenciaBT(String sospechoso,String arma,String motivo,String parte,String lugar){
        lbBT1.setText(sospechoso);
        lbBT2.setText(arma);
        lbBT3.setText(motivo);
        lbBT4.setText(parte);
        lbBT5.setText(lugar);
        String str = txtBT.getText() + "\n"+"["+sospechoso+","+arma+","+motivo+","+parte+","+lugar+"]";
        txtBT.setText(str);
    }
    public void solucionBT(String solucion){
        String str = txtBT.getText() + "\n"+solucion;
        txtBT.setText(str);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        juego.btnIniciar((int)jSpinner1.getValue());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbBT1;
    private javax.swing.JLabel lbBT2;
    private javax.swing.JLabel lbBT3;
    private javax.swing.JLabel lbBT4;
    private javax.swing.JLabel lbBT5;
    private javax.swing.JLabel lbFB1;
    private javax.swing.JLabel lbFB2;
    private javax.swing.JLabel lbFB3;
    private javax.swing.JLabel lbFB4;
    private javax.swing.JLabel lbFB5;
    private javax.swing.JTextArea txtBT;
    private javax.swing.JTextArea txtFB;
    private javax.swing.JLabel txtSolucion;
    // End of variables declaration//GEN-END:variables
}
